# Generated by Django 5.0.6 on 2024-06-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParaisoVerde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
