# Generated by Django 5.0.6 on 2024-06-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParaisoVerde', '0002_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
