# Generated by Django 5.0.6 on 2024-07-04 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParaisoVerde', '0003_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['usuario']},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'ordering': ['compra']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'ordering': ['usuario']},
        ),
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_inicio_suscripcion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
