# Generated by Django 5.0.6 on 2024-07-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppParaisoVerde', '0004_alter_compra_options_alter_detallecompra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='descontado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
