from django.urls import path
from . import views
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('iniciarSesion/', views.iniciarSesion, name='iniciarSesion'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('registro/', views.registro, name='registro'),
    path('productos/', views.productos, name='productos'),
    path('administrar/', views.administrar, name='administrar'),
    path('MiPerfil/', views.MiPerfil, name='MiPerfil'),
    path('crearUsuario/', views.crearUsuario, name='crearUsuario'),
    path('abrirSesion/', views.abrirSesion, name='abrirSesion'),
    path('ObtenerSesion/', views.ObtenerSesion, name='ObtenerSesion'),
    path('AdminCrearUsuario/', views.AdminCrearUsuario, name='AdminCrearUsuario'),
    path('AdminCrearTipoUsuario/', views.AdminCrearTipoUsuario, name='AdminCrearTipoUsuario'),
    path('AdminBuscarTiposUsuario/', views.AdminBuscarTiposUsuario, name='AdminBuscarTiposUsuario'),
    path('AdminEliminarTipoUsuario/', views.AdminEliminarTipoUsuario, name='AdminEliminarTipoUsuario'),
    path('AdminBuscarTipoUsuarioEditar/', views.AdminBuscarTipoUsuarioEditar, name='AdminBuscarTipoUsuarioEditar'),
    path('AdminEditarTipoUsuario/', views.AdminEditarTipoUsuario, name='AdminEditarTipoUsuario'),
    path('AdminBuscarTiposProducto/', views.AdminBuscarTiposProducto, name='AdminBuscarTiposProducto'),
    path('AdminCrearTipoProducto/', views.AdminCrearTipoProducto, name='AdminCrearTipoProducto'),
    path('AdminEliminarTipoProducto/', views.AdminEliminarTipoProducto, name='AdminEliminarTipoProducto'),
    path('AdminBuscarTipoProductoEditar/', views.AdminBuscarTipoProductoEditar, name='AdminBuscarTipoProductoEditar'),
    path('AdminEditarTipoProducto/', views.AdminEditarTipoProducto, name='AdminEditarTipoProducto'),
    path('AdminBuscarTiposUsuarioCMB/', views.AdminBuscarTiposUsuarioCMB, name='AdminBuscarTiposUsuarioCMB'),
    path('AdminBuscarUsuarios/', views.AdminBuscarUsuarios, name='AdminBuscarUsuarios'),
    path('AdminEliminarUsuario/', views.AdminEliminarUsuario, name='AdminEliminarUsuario'),
    path('AdminBuscarUsuarioEditar/', views.AdminBuscarUsuarioEditar, name='AdminBuscarUsuarioEditar'),
    path('AdminEditarUsuario/', views.AdminEditarUsuario, name='AdminEditarUsuario'),
    path('cerrarSesion/', views.cerrarSesion, name='cerrarSesion'),
    path('AdminBuscarTiposProductoCMB/', views.AdminBuscarTiposProductoCMB, name='AdminBuscarTiposProductoCMB'),
    path('AdminCrearProducto/', views.AdminCrearProducto, name='AdminCrearProducto'),
    path('AdminBuscarProductos/', views.AdminBuscarProductos, name='AdminBuscarProductos'),
    path('AdminBuscarProductoEditar/', views.AdminBuscarProductoEditar, name='AdminBuscarProductoEditar'),
    path('AdminEditarProducto/', views.AdminEditarProducto, name='AdminEditarProducto'),
    path('AdminEliminarProducto/', views.AdminEliminarProducto, name='AdminEliminarProducto'),
    path('buscarProductosComprar/', views.buscarProductosComprar, name='buscarProductosComprar'),
    path('FiltrarProductos/', views.FiltrarProductos, name='FiltrarProductos'),
    path('AgregarProductoCarro/', views.AgregarProductoCarro, name='AgregarProductoCarro'),
    path('ObtenerCantidadProductosCarro/', views.ObtenerCantidadProductosCarro, name='ObtenerCantidadProductosCarro'),
    path('carrito/', views.carrito, name='carrito'),
    path('BuscarProductosCarrito/', views.BuscarProductosCarrito, name='BuscarProductosCarrito'),
    path('EliminarProductoCarrito/', views.EliminarProductoCarrito, name='EliminarProductoCarrito'),
    path('AdminBuscarUsuariosCMB/', views.AdminBuscarUsuariosCMB, name='AdminBuscarUsuariosCMB'),
    path('AdminCrearSuscripcion/', views.AdminCrearSuscripcion, name='AdminCrearSuscripcion'),
    path('AdminBuscarSuscripciones/', views.AdminBuscarSuscripciones, name='AdminBuscarSuscripciones'),
    path('AdminEliminarSuscripcion/', views.AdminEliminarSuscripcion, name='AdminEliminarSuscripcion'),
    path('UsuarioSuscrito/', views.UsuarioSuscrito, name='UsuarioSuscrito'),
    path('ComprarCarrito/', views.ComprarCarrito, name='ComprarCarrito'),
    path('CancelarSuscripcion/', views.CancelarSuscripcion, name='CancelarSuscripcion'),
    path('Suscribirse/', views.Suscribirse, name='Suscribirse'),
    path('BuscarInformacionUsuario/', views.BuscarInformacionUsuario, name='BuscarInformacionUsuario'),
    path('BuscarMisCompras/', views.BuscarMisCompras, name='BuscarMisCompras'),
    path('ImprimirDetalleCompra/', views.ImprimirDetalleCompra, name='ImprimirDetalleCompra'),
    path('AdminBuscarProductosCMB/', views.AdminBuscarProductosCMB, name='AdminBuscarProductosCMB'),
    path('AdminAgregarPromocion/', views.AdminAgregarPromocion, name='AdminAgregarPromocion'),
    path('AdminBuscarPromociones/', views.AdminBuscarPromociones, name='AdminBuscarPromociones'),
    path('AdminEliminarPromocion/', views.AdminEliminarPromocion, name='AdminEliminarPromocion'),
    path('AdminBuscarPromocionEditar/', views.AdminBuscarPromocionEditar, name='AdminBuscarPromocionEditar'),
    path('AdminEditarPromocion/', views.AdminEditarPromocion, name='AdminEditarPromocion'),
]